import { default as colors } from "./colors";

const theme = {
    colors,
    labelTextColor: colors.white,
    buttonBackground: "rgba(0, 0, 0, 0.3)",
    buttonBorder: `1px solid ${colors["light-grey"]}`,
    primaryFont: "Averta",
    buttonFontWeight: 500,
    accent: colors.glint,
    secondaryAccent: colors["refracted-cyan"],
    errorColor: "#ff3838",
    focusedTextColor: colors["rich-black"],
    focusedSubtextColor: "#ffffff",
    unfocusedTextColor: colors["light-grey-100"],

/*
    secondaryFont: "Averta",
    "legal-text-unfocused-color": colors[medium-grey,
    "charcoal-grey": colors[charcoal-grey,
    "charcoal-grey-50": colors[charcoal-grey-50,
    "large-line-height": colors[line-height-normal,
    "line-height-normal": colors[line-height-normal,
    "meta-data-color": colors[light-grey-100,
    "focus-color": colors[glint,
    "secondary-color": colors[light-grey,
    "light-grey": colors[light-grey,
    "header-bg-color": colors[dark-umbra,
    "nav-font-size": 24px,
    "content-detail-color": colors[light-grey,
    "black-800": colors[black-800,
    "progress-bar-bg-color": colors[medium-grey,
    "progress-bar-color": colors[progress-bar-gradient,
    "progress-bar-thumb": colors[refracted-cyan,
    "nav-background": colors[nav-background,
    "back-drop-blur": colors[nav-back-drop-blur,
    "movie-detail-color": colors[light-grey,
    "user-input-font-size": 36px,
    "user-input-icon-size": 40px,
    "toggle-button-disabled": rgba(82, 82, 83, 0.85),
    "toggle-button-disabled-text": colors[light-grey,
    "toggle-button-unfocused": white,
    "toggle-button-focused": colors[glint,
    "series-info-cast": colors[light-grey,
    "icons-tags-hd": colors[light-grey,
    "add-profile-background-color": colors[dark-umbra,
    "add-profile-text-color": white,
    "swimlane-block-bg-color": transparent,
    "bg-mask": #0d2224,
    "label-text-color": white,
    "text-emphasis-color": white,
    "info-text-color": colors[light-grey,
    "modal-overlay": rgba(colors[dark-umbra, 0.8),
    "modal-background": colors[rich-black,
    "keyboard-background": colors[rich-black,
    "keyboard-key-background": colors[dark-umbra,
    "keyboard-key-border": 2px solid colors[charcoal-grey-20,
    "category-grid-view-all-border": solid 3px colors[light-grey,
    "category-grid-view-all-background": rgba(0, 0, 0, 0.3),
    "browse-by-imgs": colors[browse-by-imgs,
    "border-radius-primary": 8px,
    "browse-font-size": 24px,
    "view-all-filter-background": colors[rich-black,
    "view-all-filter-section-background": colors[dark-umbra,
    "badge-gradient": colors[badge-gradient,
    "badge-text-color": colors[dark-umbra,
    "video-ui-bg-color": rgba(colors[dark-umbra, 0.7),
    "video-ui-gradient-color": rgba(colors[dark-umbra, 0.85),
    "video-ui-minimized-color-end": colors[dark-umbra,
    "image-fade-overlay": rgba(colors[dark-umbra, 0.8),
    "progress-bar-cyan-color": colors[refracted-cyan,
    "settings-header-border": 2px solid colors[charcoal-grey-50,
    "asset-tabs-bg": linear-gradient(transparent 0%, rgba(colors[dark-umbra, 0.6) 24%, rgba(colors[dark-umbra, 1) 78%),
    "screen-saver-gradient": colors[screen-saver-gradient,
    "cpra-banner-background": linear-gradient(to right, #415b63, #5d757d),
    "background-image-mask": radial-gradient(circle at 64% 38%, rgba(colors[dark-umbra, 1), rgba(colors[dark-umbra, 0) 79%),
    "plan-card-background": colors[dark-umbra,
    "plan-banner-background": linear-gradient(180deg, #f1e5a5 0%, colors[refracted-cyan 51.56%),
    "plan-banner-active-bg": linear-gradient(180deg, colors[light-grey 0%, white 51.56%)
*/
};

export default theme;
